### ISSUE TITLE
esx_multicharacter

### ISSUE THREAD

**Issue by thelindat** [zaphosting/esx_12_recipe#1]
This is the only resource still maintained outside the esx-legacy repo, and it's received a lot of changes since then.
It would be worthwhile either updating the recipe to download the latest, or merging the changes into the zap repo.

https://github.com/thelindat/esx_multicharacter

**Comment by Blumlaut** [comment]
Usually we tend to not do such "major" changes to a resource to prevent pushing broken custom scripts, i'll make a testenv with your fork and see if its feasible to implement into https://github.com/zap-fivem/esx_12, main concern would just be breaking existing installs.
